version: 0.2

env:
  variables:
    MAVEN_OPTS: "-Dmaven.test.failure.ignore=true"  # Optional: Continue the build even if tests fail

phases:
  install:
    runtime-versions:
      java: corretto11  # Specify the Java version you need; change to `corretto8` or another as needed
    commands:
      - echo "Installing Maven..."
      - yum install -y maven

  pre_build:
    commands:
      - echo "Starting the build process..."
      - echo "Resolving dependencies with debug info..."
      - mvn -X dependency:resolve  # Added -X for debugging
      - mvn clean  # Cleans up any previous builds

  build:
    commands:
      - echo "Compiling the application..."
      - mvn compile  # Compiles the Java source code
      - echo "Running unit tests..."
      - mvn test  # Runs tests; adjust the MAVEN_OPTS environment variable to skip tests if needed
      - echo "Packaging the application..."
      - mvn package  # Packages the code into a JAR/WAR file

  post_build:
    commands:
      - echo "Build completed on `date`."
      - echo "Collecting artifacts..."

artifacts:
  files:
    - target/*.jar  # Modify this to `target/*.war` if you're building a WAR file for web applications
  discard-paths: yes  # Stores artifacts without preserving directory structure

cache:
  paths:
    - /root/.m2/**/*  # Caches Maven dependencies to speed up future builds
