version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - echo Installing Maven
      - yum install -y maven  # Change to yum for Amazon Linux
  build:
    commands:
      - echo Building the Java app
      - mvn clean package
  post_build:
    commands:
      - echo Build completed. Uploading artifacts to S3.
artifacts:
  files:
    - "*.jar"    # This matches JAR files inside the target directory
  base-directory: target  # Corrected to remove any spaces
  discard-paths: yes  # This ensures that artifacts are stored without folder paths
